apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  labels:
    app: api
spec:
  # ClusterIP = expose chỉ bên trong K8s cluster
  # (Client Pod sẽ dùng api-service:8080 để kết nối)
  type: ClusterIP
  selector:
    # Route traffic đến Pods có label app: api
    app: api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
